from creature_stats import NUM_UPGRADEABLE_STATS
from action_kind import ACTION_KINDS_COUNT

PARAMS_SNAP_DIR_START = 0
PARAMS_SNAP_DIR_X_START = PARAMS_SNAP_DIR_START
PARAM_REPRODUCE_DX = 0
PARAM_ATTACK_DX = 1
PARAMS_SNAP_DIR_X_END = 2

PARAMS_SNAP_DIR_Y_START = 2
PARAM_REPRODUCE_DY = 2
PARAM_ATTACK_DY = 3
PARAMS_SNAP_DIR_Y_END = 4
PARAMS_SNAP_DIR_END = PARAMS_SNAP_DIR_Y_END

PARAMS_TANH_START = 4
PARAM_MOVE_DX = 4
PARAM_MOVE_DY = 5
PARAMS_TANH_END = 6

PARAMS_MASS_FRACTIONS_START = 6
PARAM_OFFSPRING_MASS_FRACTION = 6
PARAM_HEAL_MASS_FRACTION = 7

PARAMS_UPGRADE_MASS_FRACTIONS_START = 8
PARAMS_UPGRADE_MASS_FRACTIONS_END = PARAMS_UPGRADE_MASS_FRACTIONS_START + NUM_UPGRADEABLE_STATS
PARAMS_MASS_FRACTIONS_END = PARAMS_UPGRADE_MASS_FRACTIONS_END

PARAMS_COUNT = PARAMS_MASS_FRACTIONS_END

COUNT = ACTION_KINDS_COUNT + PARAMS_COUNT